keys:
  # Public Age Key 'host_nova'
  - &host_nova "age1j809mn4m29jve59c54flhz2vdpy6mxn8j230m64rg0238fs4vfysa4kj6x"
  # Public Age Key 'haku_nova'
  - &haku_nova "age1eycv5vdxaze35ux64p8rmgvpdvfv3t4vtr8k7plfe3cwrd9edalsqu4l3u"
creation_rules:
  # Alle Dateien im Ordner 'secrets', die auf .yaml enden, werden mit diesem Key verschlüsselt
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *host_nova
        - *haku_nova
