services:
  # 1. Der einfache, stabile Proxy OHNE File-Descriptor Limits
  #socket-proxy:
  #  image: alpine/socat
  #  container_name: socket-proxy
  #  restart: unless-stopped
  #  user: "0:0"
  #  command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
  #  volumes:
  #    - /tmp/podman_run/podman.sock:/var/run/docker.sock

  gitea:
    image: docker.io/gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - /mnt/data/gitea:/data

  adguard:
    image: docker.io/adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3001:3000/tcp"
      - "8080:80/tcp"
    volumes:
      - /mnt/data/adguard/work:/opt/adguardhome/work
      - /mnt/data/adguard/conf:/opt/adguardhome/conf

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    user: "0:0" # <- Beibehalten für sicheren Secret-Zugriff
    depends_on:
      - adguard
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=192.168.178.69:3002,192.168.178.69
      - HOMEPAGE_VAR_ADGUARD_USER=haku
      - HOMEPAGE_VAR_ADGUARD_PASSWORD__FILE=/app/secrets/adguard_secret
    ports:
      - "3002:3000"
    volumes:
      - /mnt/data/homepage:/app/config
      - /tmp/podman_run/podman.sock:/var/run/docker.sock
      - /mnt/data/stacks/core/.adguard_secret:/app/secrets/adguard_secret:ro

  dockge:
    image: docker.io/louislam/dockge:latest
    container_name: dockge
    restart: unless-stopped
    user: "0:0"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "5001:5001"
    volumes:
      - /tmp/podman_run/podman.sock:/var/run/docker.sock
      - /mnt/data/dockge:/app/data
      - /mnt/data/stacks:/opt/stacks
